services:
  caddy:
    image: docker.io/caddy:2.6-alpine
    restart: unless-stopped
    volumes:
       - type: bind
         source: ${SHARE}
         target: /data
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - reverseproxy
      - mycaddy

networks:
    reverseproxy:
      name: reverseproxy
      external: true
    mycaddy:
      name: ${NETWORK}

volumes:
    myshare:
      name: ${SHARE}
