services:
  caddy:
    environment:
      - SHARE
      - NETWORK
    image: docker.io/caddy:2.7-alpine
    restart: unless-stopped
    volumes:
      - type: volume
        source: ${SHARE}
        target: /data
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - reverseproxy
      - mycaddy

networks:
    reverseproxy:
      name: reverseproxy
      external: true
    mycaddy:
      name: ${NETWORK}
